static analyzer like complain exception might thrown inside finally block saying using throw statement inside finally block break logical progression try catch finally normally agree recently come across writer try init writer write file catch exception handling finally writer writer close writer cannot closed properly writer close throw exception exception thrown probably file saved writing could declare extra set closing writer throw exception finally block work fine sure whether change drawback throwing exception inside finally block