read doc catch throw friend multiple time confess find utterly incomprehensible someone tell one would port following python snippet mathematica def safeeval fn x epsilon sys float info epsilon try first attempt return fn x except exception first exception try try second attempt return fn x epsilon except third last attempt return fn x epsilon except give raise first exception word return fn x trapping exception evaluation fn x exception cache first exception return fn x epsilon trapping exception exception second one return fn x epsilon lastly exception third one give raise first exception higher level less literal translation would return first one fn x fn x epsilon fn x epsilon evaluates without error silencing error occur along way none expression evaluates without error proceed exactly usual evaluation fn x emitting appropriate error message etc edit ok finally came solution approximates described though sure anywhere close optimal safeeval fn x epsilon machineepsilon module v sentinel v quiet check fn x check fn x epsilon check fn x epsilon sentinel v sentinel v fn x ahem thrown whole catch throw nomenclature function seem like something unnaturally tacked onto mathematica make look like widely known language